### ISSUE TITLE
打包Release失败，因为缺少两个提示禁用CS8618,CS8632

### ISSUE THREAD

**Issue by jiangjiali** [qq362946/Fantasy#11]
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
      <DefineConstants>TRACE;FANTASY_NET</DefineConstants>
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
      <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
      <NoWarn>1701;1702;IL2121;CS8603;IL2121;CS8625;IL2121;CS8618;CS8622;CS8632;CS8602;CS8603;CS8600;CS8625;CS8600;;CS8604;CS8601;SYSLIB0023</NoWarn>
    </PropertyGroup>

**Comment by qq362946** [comment]
感谢您提供的这个错误、是因为Release忘了忽略了这2个错误。现在已经修复了，你可以重新pull下试试。
