### ISSUE TITLE
IPoolMessage生成的协议Opcode为0

### ISSUE THREAD

**Issue by jiangjiali** [qq362946/Fantasy#15]
![image](https://github.com/qq362946/Fantasy/assets/7267234/28c1e0ea-b799-458d-af0c-222e6dee7a33)

![image](https://github.com/qq362946/Fantasy/assets/7267234/a06cd05c-19b5-4c5a-9b26-5020a440ccc9)

**Comment by qq362946** [comment]
不好意思、忘了说下，IPoolMessage不能定义在协议文件中、IPoolMessage只是一个过渡的接口、如果使用IPoolMessage需要自己在代码里定义协议。因为后期打算要做到全协议GC、那时候就不需要IPoolMessage了。
