### ISSUE TITLE
ServerInnerSession发送内存流到服务器内部（不支持）。

### ISSUE THREAD

**Issue by shangdibaozi** [qq362946/Fantasy#47]
由于是在开发模式下，在调用`session.Scene.NetworkMessagingComponent.CallInnerRoute`时，`Scene.GetSession`里面会因为判断到目标`Scene`在同一个`Process`下从而创建了一个`ServerInnerSession`。
接着客户端再发送一个`AddressableRPC`消息，这时候会调用到`NetworkMessagingComponent.CallInnerRoute(long entityId, long routeTypeOpCode, Type requestType, MemoryStream request)`方法，方法里面`var session = Scene.GetSession(entityId);`拿到的是`ServerInnerSession`。`ServerInnerSession`对象调用`public override void Send(MemoryStream memoryStream, uint rpcId = 0, long routeTypeOpCode = 0, long routeId = 0)`，这里面没有对消息进行解析，导致无法处理`AddressableRPC`消息。

**Comment by qq362946** [comment]
感谢您提供的这个问题，我已经发现了。马上修复。

**Comment by qq362946** [comment]
您好，在commit 9bfeff0中已经修复了您提出的问题了，非常欢迎你再次测试下。等待您的测试结果。

**Comment by shangdibaozi** [comment]
已经测试没问题，可以正常收发消息。
