### ISSUE TITLE
在使用MemoryPack定义的协议情况下，客户端协议OpCode转成的OpCodeProtocolType与序列化器匹配不上

### ISSUE THREAD

**Issue by Kakishizi** [qq362946/Fantasy#56]
![75e936e85eac3a9cf755326bf13719b4](https://github.com/user-attachments/assets/333f182b-d31c-4b0f-8b75-b646f3a3defa)
![image](https://github.com/user-attachments/assets/b51c5055-6d59-4ea5-a3cd-e45c01504f6d)
断点查看到_serializers中只保存了2个序列化器而尝试索引下标为2，导致了越界。
SerializerManager在Unity包中过滤了Bson，而且和Net包中Initialize()实现也有些区别。
Unity：
![image](https://github.com/user-attachments/assets/0b67de44-960d-4e0c-9e95-95f7d110c8f6)
Net：
![image](https://github.com/user-attachments/assets/dceb60fc-55f5-4068-b657-6ff8b6ce6090)
不知道是不是index保存逻辑的问题。

**Comment by jiangjiali** [comment]
MemoryPack 是需要自己配的吧。

**Comment by Kakishizi** [comment]
> MemoryPack 是需要自己配的吧。
导表那边是自己配置了的，对应我看了也有继承ISerialize的MemoryPack的序列化器，就是在SerializerManager初始化的时候反射查找只有两个继承ISerialize的序列化器，但是MemoryPack 的OpCode转化成查找的序列化器下标为2，不知道这是不是bug

**Comment by qq362946** [comment]
收到、稍等我测试下。

**Comment by qq362946** [comment]
您好，感谢您帮助发现并定位到这个BUG。目前该问题已成功修复，您可以尝试重新更新框架代码测试效果。如有任何疑问或进一步的反馈，随时欢迎您再次联系我！
