### ISSUE TITLE
TCP 连接问题

### ISSUE THREAD

**Issue by DvaImi** [qq362946/Fantasy#57]
使用示例项目
![QQ20241027-170445](https://github.com/user-attachments/assets/924c15fa-ef9f-41eb-97f4-7c8be971026d)

协议改成TCP
客户端做同样改动
![QQ20241027-170506](https://github.com/user-attachments/assets/e1719ebd-a432-487d-badc-60ad8ac6a9cf)

第一次连接正常，然后停止unity ，重新运行，会自动断开
![QQ20241027-170540](https://github.com/user-attachments/assets/10b9a2c2-f803-4217-b530-3cc970d43e1b)

**Comment by qq362946** [comment]
您好，感谢您帮助发现并定位到这个BUG。目前该问题已成功修复，您可以尝试重新更新框架代码测试效果。如有任何疑问或进一步的反馈，随时欢迎您再次联系我！
