### ISSUE TITLE
EntityListPool 对象好像没有用到。是有另外的用途吗？我看它是内部使用。

### ISSUE THREAD

**Issue by jiangjiali** [qq362946/Fantasy#59]
![image](https://github.com/user-attachments/assets/1d60ff90-f0b8-45cc-a143-4710aebc6544)

**Comment by qq362946** [comment]
框架内部会用到，你为什么退群了？什么情况，我加你也不理我。
因为什么原因，加我QQ聊下。

**Comment by jiangjiali** [comment]
> 框架内部会用到，你为什么退群了？什么情况，我加你也不理我。 因为什么原因，加我QQ聊下。

我想强制我到github上提问题。加了群，总是想在群里问。群里聊天不好翻记录。

**Comment by qq362946** [comment]
好的，尊重的你的决定。

**Comment by jiangjiali** [comment]
> 好的，尊重的你的决定。

等后面，我再加进qq群。

**Comment by jiangjiali** [comment]
![image](https://github.com/user-attachments/assets/f97fc7b2-2713-4212-b699-4afc183837f8)
看到了，框架内部确实有使用。
