### ISSUE TITLE
组件在Scene的初始化函数，还是保留在 内部使用比较好。

### ISSUE THREAD

**Issue by jiangjiali** [qq362946/Fantasy#60]
![image](https://github.com/user-attachments/assets/61b18d9d-06cc-460e-9ce8-523ed73600dd)

**Comment by qq362946** [comment]
您好，感谢您帮助发现并定位到这个问题。目前该问题已成功修复，您可以尝试重新更新框架代码测试效果。如有任何疑问或进一步的反馈，随时欢迎您再次联系我！
