### ISSUE TITLE
客户端的 Session?.Dispose 销毁问题

### ISSUE THREAD

**Issue by jiangjiali** [qq362946/Fantasy#67]
![e3b086146bf6e5d5e8f42c7dc4cbc419](https://github.com/user-attachments/assets/99877f75-8399-46f0-bdc5-02d2e88e946f)

昨天我测试了，还是必须在这个地方加Session销毁才行。只有这样，当网络断开，网络失败，才可以判断到session为空的状态。

**Comment by jiangjiali** [comment]
Session销毁，还必须在  base.Dispose(); 之前。

**Comment by qq362946** [comment]
您好，感谢您帮助发现并定位到这个BUG。目前该问题已成功修复，您可以尝试重新更新框架代码测试效果。如有任何疑问或进一步的反馈，随时欢迎您再次联系我！
