### ISSUE TITLE
心跳组件没有加 IsDisposed 判断

### ISSUE THREAD

**Issue by jiangjiali** [qq362946/Fantasy#68]
![image](https://github.com/user-attachments/assets/6dea0d1f-1425-40db-b704-55a44e0b1ba8)

**Comment by qq362946** [comment]
您好，感谢您帮助发现并定位到这个BUG。目前该问题已成功修复，您可以尝试重新更新框架代码测试效果。如有任何疑问或进一步的反馈，随时欢迎您再次联系我！
