### ISSUE TITLE
跳转路径错误，会把斜杠全部换为反斜杠

### ISSUE THREAD

**Issue by xianwx** [qq362946/Fantasy#72]
原因在于UnityLog.cs里的InternalEditorUtility.OpenFileAtLineExternal(fullPath.Replace('/', '\\'), line);会自主替换路径。

**Comment by xianwx** [comment]
![image](https://github.com/user-attachments/assets/dacf949d-12ef-4991-a7df-e41ef50e8ecd)
顺带一提，这里有个多余的using，且这个插件的版本如果低于2.8.3，有个严重bug，会在WebGL端自主断开连接。
然后它还有个bug，作者还在改，在服务端发了一条消息后，然后就自主断开连接，在WebGL端最后那条消息会丢失。我看群友反馈过类似的问题，不知道是不是碰巧是插件的问题。

**Comment by qq362946** [comment]
您好，感谢您帮我找到的BUG，目前这个BUG已经修复，您可以重新更新下框架代码试试，如果有任何问题欢迎你再次联系我
