### ISSUE TITLE
关于Entity 子组件存储的疑惑

### ISSUE THREAD

**Issue by TaoJiaHengOne** [qq362946/Fantasy#74]
![image](https://github.com/user-attachments/assets/956a3fe8-1b3a-4f6b-9159-8e6814356d76)
Entity 类中, 子Component 似乎根据环境存储在 最多 4个容器中, 一个Entity 会在 不同容器中出现

这样设计的初衷是什么, 减少保存时的GC 和 遍历的时间嘛

是否采用一个 容器存储 更方便一点 (保存时的GC和时间消耗个人感觉不是很重要)

**Comment by qq362946** [comment]
没错，这个问题很早我就发现了，这样确实不是很方便，所以计划要把这个给改下

**Comment by qq362946** [comment]
> ![image](https://private-user-images.githubusercontent.com/34653889/395406280-956a3fe8-1b3a-4f6b-9159-8e6814356d76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxNDYxNTMsIm5iZiI6MTczNDE0NTg1MywicGF0aCI6Ii8zNDY1Mzg4OS8zOTU0MDYyODAtOTU2YTNmZTgtMWIzYS00ZjZiLTkxNTktOGU2ODE0MzU2ZDc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDAzMTA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNWM4NjgwMTI2MmU3YTMyM2NkZGMwN2M4MjkyNGI5ZTc1OTcxZTgwZTBjMmIyOWNkMTlmNzBmYjI1NmVmYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gX_470rYHFd1-080Z1zUvtrektHnK6mxMqaJ83Sf_q8) Entity 类中, 子Component 似乎根据环境存储在 最多 4个容器中, 一个Entity 会在 不同容器中出现
> 
> 这样设计的初衷是什么, 减少保存时的GC 和 遍历的时间嘛
> 
> 是否采用一个 容器存储 更方便一点 (保存时的GC和时间消耗个人感觉不是很重要)

是因为组件分为两种：
1、普通组件，只会在运行时使用不会保存到数据库中。
2、数据库实体组件，这种情况下的组件会跟随组件保存到数据库中。

所以，如果不单独存放，每次组件保存到数据库的时候必须要遍历下当前所有组件找到哪些需要保存哪些不需要保存。
综合上面的情况下，所以我又单独做了两个来保存这些组件。

**Comment by TaoJiaHengOne** [comment]
好的 感谢解答
