### ISSUE TITLE
如何监听网络断开

### ISSUE THREAD

**Issue by TaoJiaHengOne** [qq362946/Fantasy#76]
``` C#
public class SessionDestroySystem : DestroySystem<Session>
{
    protected override void Destroy(Session session)
    {
        Log.Debug($"{session.RuntimeId} destroy \n {Environment.StackTrace}");
    }
}
```

如果使用这种方式监听 链接断开 则获取不到任何有用的信息
无法进行资源清理

**Comment by TaoJiaHengOne** [comment]
在这个 Destroy 函数中 获取的 RunTimeId 为 0
访问 Session 的RouteComponent 为null

``` java
using Fantasy;
using Fantasy.Entitas.Interface;
using Fantasy.Network;

namespace Hotfix.Gate.System;

public class SessionDestroySystem : DestroySystem<Session>
{
    protected override void Destroy(Session session)
    {
        Log.Debug($"{session.RuntimeId} destroy");
        Log.Debug($"{session.GetComponent<RouteComponent>() == null}");
    }
}
```
断开连接的结果

![image](https://github.com/user-attachments/assets/5d15fd27-0614-4f66-a9a1-1b021723b886)


在断开链接之前已经成功注册了 RouteComponent
![image](https://github.com/user-attachments/assets/ccaea5ba-9930-4af9-81a9-01afab8bd3bb)

**Comment by qq362946** [comment]
> 在这个 Destroy 函数中 获取的 RunTimeId 为 0 访问 Session 的RouteComponent 为null
> 
> ```java
> using Fantasy;
> using Fantasy.Entitas.Interface;
> using Fantasy.Network;
> 
> namespace Hotfix.Gate.System;
> 
> public class SessionDestroySystem : DestroySystem<Session>
> {
>     protected override void Destroy(Session session)
>     {
>         Log.Debug($"{session.RuntimeId} destroy");
>         Log.Debug($"{session.GetComponent<RouteComponent>() == null}");
>     }
> }
> ```
> 
> 断开连接的结果
> 
> ![image](https://private-user-images.githubusercontent.com/34653889/397300860-5d15fd27-0614-4f66-a9a1-1b021723b886.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MzQ4MjYsIm5iZiI6MTczNDgzNDUyNiwicGF0aCI6Ii8zNDY1Mzg4OS8zOTczMDA4NjAtNWQxNWZkMjctMDYxNC00ZjY2LWE5YTEtMWIwMjE3MjNiODg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDAyMjg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1YWFhM2ViNDdjM2Y0NjgyMzI2Y2E2YTViZmI4OTcxNDc5YzU4N2Q4MjJmZGRlYTg4ZWM5ODVhMTgyMGNjOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.z7On3l-xOMvzpaaYHgeSoiASN78ptGdu_D4UY1eVZ5g)
> 
> 在断开链接之前已经成功注册了 RouteComponent ![image](https://private-user-images.githubusercontent.com/34653889/397301237-ccaea5ba-9930-4af9-81a9-01afab8bd3bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MzQ4MjYsIm5iZiI6MTczNDgzNDUyNiwicGF0aCI6Ii8zNDY1Mzg4OS8zOTczMDEyMzctY2NhZWE1YmEtOTkzMC00YWY5LTgxYTktMDFhZmFiOGJkM2JiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDAyMjg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhM2MyYmU5NTI1YjRlZjZlYjJkOTg5ZDU4Y2NmZTUyMjRkMmJlNWY3YWUzZmE4NDkzZDE4Nzk2N2EwZTA3ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TT-wQewfSW-Pz5KKNmfLtey9BMZ5EVj2jYepGUhNelw)

您好，Session组件销毁顺序是先销毁子组件，也就是从最底层的组件开始销毁，然后逐渐向上销毁，也就是说当Session下的所有组件都销毁了，才会指定Session的销毁事件，所以现在你给的这个问题是正常的。一般你如果想做上面的需求，你需要单独做一个组件来实现。

**Comment by TaoJiaHengOne** [comment]
好的 谢谢 大佬指导
@qq362946 @jiangjiali

**Comment by TaoJiaHengOne** [comment]
```
using Fantasy;

namespace Entity.Gate;

/// <summary>
/// 用于记录Session 的信息
/// </summary>
public class SessionInfoComponent : Fantasy.Entitas.Entity
{
    public long SessionRid { get; private set; }

    public void SetSessionRid(long rid)
    {
        SessionRid = rid;
    }
}
```

记录以下 类似于这样的类 在Session Awake 中Add 进去
